### ISSUE TITLE
Filenames with carriage returns are improperly written to manifest

### ISSUE THREAD

**Issue by nkrabben** [tipr/bagit#20]
Any carriage return in a filename (Icon^M is a common system file with this feature) is stripped when it is written to the filename. According to the bagit spec, filenames should be percent encoded.

This was also a bug in the bagit-python and bagit-java
https://github.com/LibraryOfCongress/bagit-python/issues/12
https://github.com/LibraryOfCongress/bagit-java/issues/51

To reproduce, on the command line

```
mkdir testbag
touch testbag/Icon^M
bagit baginplace testbag
bagit verifyvalid testbag
```

To create Icon^M on the command line, press ctrl+v and then enter.

**Comment by little9** [comment]
<img width="385" alt="screen shot 2016-08-23 at 5 04 03 pm" src="https://cloud.githubusercontent.com/assets/4324761/17909717/b89b4350-6953-11e6-929c-38e5c965de3d.png">

**Comment by nkrabben** [comment]
Bagger and bagit-python add the following line to the manifest.
d41d8cd98f00b204e9800998ecf8427e  data/Icon%0D

**Comment by little9** [comment]
@nkrabben I've been working on this application over here:
https://github.com/little9/bagit

I'm not sure if @tipr is still active.
