### ISSUE TITLE
Support SHA256 and SHA512 for manifest checksums

### ISSUE THREAD

**Issue by jrgriffiniii** [tipr/bagit#33]
Currently this is supported by solutions implemented using other languages: https://github.com/LibraryOfCongress/bagit-python#configuring-bagit

**Comment by little9** [comment]
@jrgriffiniii I added support for this in version 0.4.2:

 Allow for setting the hashing algorithm:

You can choose from md5, sha1, sha256, sha512.

From the command line you can supply the hashing algo as well:

```sh
bagit add -f LICENSE.txt -a 'sha256' test
```
