### ISSUE TITLE
Ruby 3.x

### ISSUE THREAD

**Issue by pgwillia** [tipr/bagit#46]
Is there any intention of updating to work with Ruby 3.x?  If not, is there a similar gem that you might recommend?

https://github.com/tipr/bagit/blob/294a531f68c713e55d9757ea30f5f52c4a2f302f/bagit.gemspec#L17

**Comment by tbsvttr** [comment]
Is there any update on this?

**Comment by little9** [comment]
@tbsvttr I pushed an update that will allow it to run on on ruby 3.x.
