### ISSUE TITLE
Release for 0.4.6

### ISSUE THREAD

**Issue by kirkkwang** [tipr/bagit#49]
Anyway we can get a release of this gem for version 0.4.6?  I want to add it to a gemspec.

ref:
- https://github.com/tipr/bagit/commit/94c2ba74b8a57b319926f4189701e31518e961aa

**Comment by little9** [comment]
@kirkkwang I made a release for 0.4.6 and pushed the latest version to rubygems.org.

**Comment by kirkkwang** [comment]
@little9 Thank you so much!
